//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestApiGam
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVICE
    {
        public DEVICE()
        {
            this.MESSAGE = new HashSet<MESSAGE>();
            this.NOTIFICATION = new HashSet<NOTIFICATION>();
        }
    
        public int ID { get; set; }
        public string CONNECTION_ID { get; set; }
        public string DEVICE_NAME { get; set; }
        public string VHI { get; set; }
        public Nullable<System.DateTime> LAST_DATE { get; set; }
    
        public virtual ICollection<MESSAGE> MESSAGE { get; set; }
        public virtual ICollection<NOTIFICATION> NOTIFICATION { get; set; }
    }
}
