//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestApiGam
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGE
    {
        public int ID { get; set; }
        public string BODY { get; set; }
        public Nullable<int> ID_DEVICE { get; set; }
        public string AREA { get; set; }
        public bool E_S { get; set; }
        public Nullable<System.DateTime> SEND_DATE { get; set; }
    
        public virtual DEVICE DEVICE { get; set; }
    }
}
