//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestApiGam
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICATION
    {
        public int ID { get; set; }
        public int ID_DEVICE { get; set; }
        public int ID_TYPE { get; set; }
        public System.DateTime DATE { get; set; }
    
        public virtual DEVICE DEVICE { get; set; }
        public virtual NOTIFICATION_TYPE NOTIFICATION_TYPE { get; set; }
    }
}
