//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestApiGam
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICATION_TYPE
    {
        public NOTIFICATION_TYPE()
        {
            this.NOTIFICATION = new HashSet<NOTIFICATION>();
        }
    
        public int ID { get; set; }
        public string NOT_CODE { get; set; }
    
        public virtual ICollection<NOTIFICATION> NOTIFICATION { get; set; }
    }
}
